name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: check out repositoy code
        uses: actions/checkout@v3

      - name: print hello hello-world
        run: echo "$(cat hello-world.txt)"